//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmojiCards.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EmojiCards.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New note .
        /// </summary>
        internal static string AddNewNotePageTitle {
            get {
                return ResourceManager.GetString("AddNewNotePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string ChangeLanguagePageBtnSave {
            get {
                return ResourceManager.GetString("ChangeLanguagePageBtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change language.
        /// </summary>
        internal static string ChangeLanguagePageTitle {
            get {
                return ResourceManager.GetString("ChangeLanguagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash cards.
        /// </summary>
        internal static string GamesMenuPageButtonFlashCards {
            get {
                return ResourceManager.GetString("GamesMenuPageButtonFlashCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guess me.
        /// </summary>
        internal static string GamesMenuPageButtonGuessMe {
            get {
                return ResourceManager.GetString("GamesMenuPageButtonGuessMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound cards.
        /// </summary>
        internal static string GamesMenuPageButtonSoundCards {
            get {
                return ResourceManager.GetString("GamesMenuPageButtonSoundCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GAMES.
        /// </summary>
        internal static string GamesMenuPageLabelGames {
            get {
                return ResourceManager.GetString("GamesMenuPageLabelGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games menu.
        /// </summary>
        internal static string GamesMenuPageTitle {
            get {
                return ResourceManager.GetString("GamesMenuPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password?.
        /// </summary>
        internal static string LoginPageAlertForgotPassword {
            get {
                return ResourceManager.GetString("LoginPageAlertForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email or password!.
        /// </summary>
        internal static string LogInPageAlertInvalidCredentials {
            get {
                return ResourceManager.GetString("LogInPageAlertInvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to continue, please check your email for verification..
        /// </summary>
        internal static string LogInPageAlertVerifyEmail {
            get {
                return ResourceManager.GetString("LogInPageAlertVerifyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong password..
        /// </summary>
        internal static string LogInPageAlertWrongPassword {
            get {
                return ResourceManager.GetString("LogInPageAlertWrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        internal static string LogInPageBtnLogIn {
            get {
                return ResourceManager.GetString("LogInPageBtnLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please log in with valid email address and password..
        /// </summary>
        internal static string LogInPageLabelLogIn {
            get {
                return ResourceManager.GetString("LogInPageLabelLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to sign up..
        /// </summary>
        internal static string LogInPageLabelPleaseRegister {
            get {
                return ResourceManager.GetString("LogInPageLabelPleaseRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        internal static string LogInPageTitle {
            get {
                return ResourceManager.GetString("LogInPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games.
        /// </summary>
        internal static string MenuPageBtnGames {
            get {
                return ResourceManager.GetString("MenuPageBtnGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string MenuPageBtnInfo {
            get {
                return ResourceManager.GetString("MenuPageBtnInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string MenuPageBtnNotes {
            get {
                return ResourceManager.GetString("MenuPageBtnNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MENU.
        /// </summary>
        internal static string MenuPageLabelMenu {
            get {
                return ResourceManager.GetString("MenuPageLabelMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string MenuPageTitle {
            get {
                return ResourceManager.GetString("MenuPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this note?.
        /// </summary>
        internal static string NoteDetailsPageAlertConfirmationDeleteNote {
            get {
                return ResourceManager.GetString("NoteDetailsPageAlertConfirmationDeleteNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string NoteDetailsPageBtnDeleteNote {
            get {
                return ResourceManager.GetString("NoteDetailsPageBtnDeleteNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string NoteDetailsPageBtnUpdateNote {
            get {
                return ResourceManager.GetString("NoteDetailsPageBtnUpdateNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit note.
        /// </summary>
        internal static string NoteDetailsPageTitle {
            get {
                return ResourceManager.GetString("NoteDetailsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to log out?.
        /// </summary>
        internal static string NotesPageAlertSureToLogOut {
            get {
                return ResourceManager.GetString("NotesPageAlertSureToLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due to safety reasons please log in again..
        /// </summary>
        internal static string NotesPageAlertTokenExpired {
            get {
                return ResourceManager.GetString("NotesPageAlertTokenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        internal static string NotesPageButtonLogOut {
            get {
                return ResourceManager.GetString("NotesPageButtonLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of notes.
        /// </summary>
        internal static string NotesPageLabelListOfNotes {
            get {
                return ResourceManager.GetString("NotesPageLabelListOfNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string NotesPageTitle {
            get {
                return ResourceManager.GetString("NotesPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your email to change your password..
        /// </summary>
        internal static string ResetPasswordPageAlertCheckEmail {
            get {
                return ResourceManager.GetString("ResetPasswordPageAlertCheckEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string ResetPasswordPageBtnSend {
            get {
                return ResourceManager.GetString("ResetPasswordPageBtnSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email adress in order to change your password..
        /// </summary>
        internal static string ResetPasswordPageLabelEnterEmail {
            get {
                return ResourceManager.GetString("ResetPasswordPageLabelEnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        internal static string ResetPasswordPageTitle {
            get {
                return ResourceManager.GetString("ResetPasswordPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert!.
        /// </summary>
        internal static string SharedAlertAlert {
            get {
                return ResourceManager.GetString("SharedAlertAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill all the blanks!.
        /// </summary>
        internal static string SharedAlertFIllBlanks {
            get {
                return ResourceManager.GetString("SharedAlertFIllBlanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string SharedAlertNo {
            get {
                return ResourceManager.GetString("SharedAlertNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string SharedAlertOk {
            get {
                return ResourceManager.GetString("SharedAlertOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration succeeded! Please check your email address for verification..
        /// </summary>
        internal static string SharedAlertRegistrationSucceeded {
            get {
                return ResourceManager.GetString("SharedAlertRegistrationSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Please try again..
        /// </summary>
        internal static string SharedAlertSomethingWentWrong {
            get {
                return ResourceManager.GetString("SharedAlertSomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uknown email address!.
        /// </summary>
        internal static string SharedAlertUnknownEmail {
            get {
                return ResourceManager.GetString("SharedAlertUnknownEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string SharedAlertYes {
            get {
                return ResourceManager.GetString("SharedAlertYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add note.
        /// </summary>
        internal static string SharedButtonAddNote {
            get {
                return ResourceManager.GetString("SharedButtonAddNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANGRY.
        /// </summary>
        internal static string SharedModelAngry {
            get {
                return ResourceManager.GetString("SharedModelAngry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONFUSED.
        /// </summary>
        internal static string SharedModelConfused {
            get {
                return ResourceManager.GetString("SharedModelConfused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRY.
        /// </summary>
        internal static string SharedModelCry {
            get {
                return ResourceManager.GetString("SharedModelCry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HAPPY.
        /// </summary>
        internal static string SharedModelHappy {
            get {
                return ResourceManager.GetString("SharedModelHappy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HUNGRY.
        /// </summary>
        internal static string SharedModelHungry {
            get {
                return ResourceManager.GetString("SharedModelHungry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAD.
        /// </summary>
        internal static string SharedModelSad {
            get {
                return ResourceManager.GetString("SharedModelSad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHY.
        /// </summary>
        internal static string SharedModelShy {
            get {
                return ResourceManager.GetString("SharedModelShy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMILING.
        /// </summary>
        internal static string SharedModelSmiling {
            get {
                return ResourceManager.GetString("SharedModelSmiling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SURPRISED.
        /// </summary>
        internal static string SharedModelSurprised {
            get {
                return ResourceManager.GetString("SharedModelSurprised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THIRSTY.
        /// </summary>
        internal static string SharedModelThirsty {
            get {
                return ResourceManager.GetString("SharedModelThirsty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string SharedPlaceholderDescription {
            get {
                return ResourceManager.GetString("SharedPlaceholderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string SharedPlaceholderEmail {
            get {
                return ResourceManager.GetString("SharedPlaceholderEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string SharedPlaceholderPassword {
            get {
                return ResourceManager.GetString("SharedPlaceholderPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string SharedPlaceholderTitle {
            get {
                return ResourceManager.GetString("SharedPlaceholderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email already exists. Please sign up with a new one..
        /// </summary>
        internal static string SignUpPageAlertEmailExists {
            get {
                return ResourceManager.GetString("SignUpPageAlertEmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid email adress..
        /// </summary>
        internal static string SignUpPageAlertInvalidCredentials {
            get {
                return ResourceManager.GetString("SignUpPageAlertInvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter stonger password..
        /// </summary>
        internal static string SignUpPageAlertWeakPassword {
            get {
                return ResourceManager.GetString("SignUpPageAlertWeakPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        internal static string SignUpPageBtnSignUp {
            get {
                return ResourceManager.GetString("SignUpPageBtnSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill the following form to register..
        /// </summary>
        internal static string SignUpPageLabelFillForm {
            get {
                return ResourceManager.GetString("SignUpPageLabelFillForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        internal static string SignUpPageTitle {
            get {
                return ResourceManager.GetString("SignUpPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t go back..
        /// </summary>
        internal static string SoundCardsGamePageAlertCantGoBack {
            get {
                return ResourceManager.GetString("SoundCardsGamePageAlertCantGoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to play again?.
        /// </summary>
        internal static string SoundCardsGamePageAlertPlayAgain {
            get {
                return ResourceManager.GetString("SoundCardsGamePageAlertPlayAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound Cards.
        /// </summary>
        internal static string SoundCardsGamePageTitle {
            get {
                return ResourceManager.GetString("SoundCardsGamePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Language.
        /// </summary>
        internal static string WelcomePageBtnChangeLang {
            get {
                return ResourceManager.GetString("WelcomePageBtnChangeLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string WelcomePageBtnContinue {
            get {
                return ResourceManager.GetString("WelcomePageBtnContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome!.
        /// </summary>
        internal static string WelcomePageTitle {
            get {
                return ResourceManager.GetString("WelcomePageTitle", resourceCulture);
            }
        }
    }
}
